name: scorecard-dependency-analysis

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  dependency-analysis:
    name: Scorecards dependency analysis
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          persist-credentials: false
      - name: Print environment variables
        run: |
          echo "GITHUB_PR_NUMBER: $GITHUB_PR_NUMBER"
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY_OWNER
          echo $GITHUB_ACTOR
        shell: bash

      - name: Run analysis
        uses: ossf/scorecard-dependencyanalysis@dependency-analysis # dependency-analysis
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
